---

- name: Install k3s on new host
  hosts: k3s_cluster
  become: yes
  vars_files:
    - vars/vault.yaml

  tasks:
  - name: Update cache (distro agnostic)
    ansible.builtin.package:
      update_cache: yes
    when: ansible_pkg_mgr in ['apt', 'yum', 'dnf']

  - name: Install pre-reqs
    ansible.builtin.package:
      name:
        - curl
      state: latest


  - name: Download and run the install script, and set up k3s as a agent(worker)
    ansible.builtin.shell: |
      curl -sfL https://get.k3s.io | K3S_URL={{ k3s_master_node_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -
    args:
      creates: /etc/systemd/system/k3s-agent.service
